####################################################################################################
#####                                    Car Assistant                                         #####
#####                  Repository: https://github.com/ShonP40/Car-Assistant                    #####
####################################################################################################
##### Purpose: WiFi hotspot config                                                             #####
####################################################################################################
##### NOTE:                                                                                    #####
##### - Make changes ONLY if absolutely necessary and you have the required knowledge.         #####
##### - For normal system use, modifications to this file are NOT required.                    #####
####################################################################################################

wifi:
  ap:
    ssid: ${wifi_hotspot_ssid}
    password: ${wifi_hotspot_password}